import { Party } from "./storage";

export const initialParties: Party[] = [
  {
    id: "1",
    title: "Golden Hour Rooftop Gathering",
    date: "2025-10-17",
    time: "19:00",
    location: "Manhattan",
    city: "New York",
    host: "Sarah Johnson",
    hostId: "host1",
    price: 45,
    capacity: 20,
    attendees: 11,
    ageRange: "21-35",
    type: "Rooftop Party",
    description: "Join us for an unforgettable evening at our exclusive rooftop party with stunning Manhattan skyline views",
    images: ["https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800"],
    tags: ["rooftop", "sunset", "cocktails"],
    rating: 4.8,
    reviews: 24
  },
  {
    id: "2",
    title: "The Ultimate House Party",
    date: "2025-10-17",
    time: "20:00",
    location: "Brooklyn",
    city: "New York",
    host: "Mike Chen",
    hostId: "host2",
    price: 50,
    capacity: 25,
    attendees: 14,
    ageRange: "23-34",
    type: "House Party",
    description: "Music, laughter, and great vibes all night long at our Brooklyn loft",
    images: ["https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800"],
    tags: ["music", "dance", "drinks"],
    rating: 4.9,
    reviews: 31
  },
  {
    id: "3",
    title: "Tipsy Twinkles - Pre-Halloween Bash",
    date: "2025-10-17",
    time: "18:30",
    location: "West Hollywood",
    city: "Los Angeles",
    host: "Jessica Martinez",
    hostId: "host3",
    price: 42,
    capacity: 20,
    attendees: 12,
    ageRange: "21-35",
    type: "House Party",
    description: "Get ready for Halloween with costumes, cocktails, and spooky vibes",
    images: ["https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800"],
    tags: ["halloween", "costumes", "themed"],
    rating: 4.7,
    reviews: 18
  },
  {
    id: "4",
    title: "Twilight Tales - Evening Gathering",
    date: "2025-10-18",
    time: "19:00",
    location: "Downtown",
    city: "Chicago",
    host: "David Kim",
    hostId: "host4",
    price: 38,
    capacity: 20,
    attendees: 11,
    ageRange: "21-35",
    type: "House Party",
    description: "An intimate evening of storytelling, music, and connection",
    images: ["https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=800"],
    tags: ["intimate", "storytelling", "music"],
    rating: 4.6,
    reviews: 15
  },
  {
    id: "5",
    title: "Sunset Social - Rooftop Vibes",
    date: "2025-10-18",
    time: "17:00",
    location: "Marina District",
    city: "San Francisco",
    host: "Emily Rodriguez",
    hostId: "host5",
    price: 55,
    capacity: 30,
    attendees: 18,
    ageRange: "25-40",
    type: "Rooftop Party",
    description: "Watch the sunset over the Golden Gate Bridge with cocktails and good company",
    images: ["https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800"],
    tags: ["rooftop", "sunset", "views"],
    rating: 4.9,
    reviews: 42
  },
  {
    id: "6",
    title: "Night Vibes - Dance & Music Party",
    date: "2025-10-19",
    time: "20:00",
    location: "Downtown",
    city: "Miami",
    host: "Carlos Santos",
    hostId: "host6",
    price: 48,
    capacity: 25,
    attendees: 15,
    ageRange: "21-35",
    type: "House Party",
    description: "Dance the night away with live DJ and amazing energy",
    images: ["https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800"],
    tags: ["dance", "dj", "music"],
    rating: 4.8,
    reviews: 28
  },
  {
    id: "7",
    title: "Brunch & Beats - Weekend Brunch Party",
    date: "2025-10-20",
    time: "11:00",
    location: "Austin",
    city: "Austin",
    host: "Amanda Lee",
    hostId: "host7",
    price: 35,
    capacity: 15,
    attendees: 8,
    ageRange: "25-40",
    type: "Brunch Party",
    description: "Start your weekend right with mimosas, great food, and chill vibes",
    images: ["https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800"],
    tags: ["brunch", "mimosas", "weekend"],
    rating: 4.7,
    reviews: 22
  },
  {
    id: "8",
    title: "Game Night Extravaganza",
    date: "2025-10-20",
    time: "18:00",
    location: "Capitol Hill",
    city: "Seattle",
    host: "Ryan Park",
    hostId: "host8",
    price: 30,
    capacity: 16,
    attendees: 10,
    ageRange: "21-35",
    type: "House Party",
    description: "Board games, card games, and video games with pizza and drinks",
    images: ["https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800"],
    tags: ["games", "casual", "fun"],
    rating: 4.6,
    reviews: 19
  },
  {
    id: "9",
    title: "Cocktail & Chill - Mixology Night",
    date: "2025-10-21",
    time: "19:30",
    location: "Back Bay",
    city: "Boston",
    host: "Olivia Brown",
    hostId: "host9",
    price: 60,
    capacity: 20,
    attendees: 12,
    ageRange: "25-40",
    type: "House Party",
    description: "Learn cocktail making from a professional mixologist",
    images: ["https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800"],
    tags: ["cocktails", "mixology", "upscale"],
    rating: 4.9,
    reviews: 35
  },
  {
    id: "10",
    title: "K-Pop Dance Party",
    date: "2025-10-22",
    time: "20:00",
    location: "Koreatown",
    city: "Los Angeles",
    host: "Jenny Kim",
    hostId: "host10",
    price: 40,
    capacity: 25,
    attendees: 16,
    ageRange: "18-30",
    type: "House Party",
    description: "Dance to the latest K-Pop hits with fellow fans",
    images: ["https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800"],
    tags: ["kpop", "dance", "music"],
    rating: 4.8,
    reviews: 27
  },
  {
    id: "11",
    title: "Wine & Dine - Wine Pairing Party",
    date: "2025-10-23",
    time: "19:00",
    location: "Napa Valley",
    city: "San Francisco",
    host: "Thomas Anderson",
    hostId: "host11",
    price: 75,
    capacity: 15,
    attendees: 9,
    ageRange: "28-45",
    type: "House Party",
    description: "Exclusive wine tasting with gourmet food pairings",
    images: ["https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800"],
    tags: ["wine", "gourmet", "upscale"],
    rating: 5.0,
    reviews: 41
  },
  {
    id: "12",
    title: "Retro Night - 80s/90s Throwback",
    date: "2025-10-24",
    time: "20:00",
    location: "Lower East Side",
    city: "New York",
    host: "Lisa Thompson",
    hostId: "host12",
    price: 45,
    capacity: 22,
    attendees: 13,
    ageRange: "25-40",
    type: "House Party",
    description: "Dress up in your best 80s/90s outfit and party like it's 1999",
    images: ["https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800"],
    tags: ["retro", "themed", "dance"],
    rating: 4.7,
    reviews: 23
  }
];

