services:
  - type: web
    name: partyconnect
    env: node
    region: oregon
    plan: free
    buildCommand: pnpm install && cd client && pnpm exec vite build
    startCommand: node server/index.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1

